language: minimal
services: docker

matrix:
  include:
    - env: ARCH='amd64'   DOCKER_IMAGE='alpine'
    - env: ARCH='i386'    DOCKER_IMAGE='i386/alpine'
    - env: ARCH='aarch64' DOCKER_IMAGE='alpine'
      arch: arm64

script:
  - ./.ci/docker_build.sh "$DOCKER_IMAGE" "$ARCH"

deploy:
  api_key:
    secure: $GITHUB_OAUTH
  file_glob: true
  file: pegh-*
  on:
    tags: true
  provider: releases
  skip_cleanup: true
